### ISSUE TITLE
Fix RabbitMQ missing on b1, c1 and d1

### ISSUE THREAD

**Issue by Kirsten-Osborn** [filetrust/Glasswall-ICAP-Platform#310]
When scaling a deployment from 3 to 9 clusters

https://github.com/filetrust/program-icap/issues/189

Review solution options

**Comment by sirspen** [comment]
I've created a pull request to solve this issue. Tass has reviewed and merged it. The change is in the develop branch now and can be found here: https://github.com/sirspen/Glasswall-ICAP-Platform/blob/1f7807962081dedda789418689826fa551447e4f/modules/rancher/helm-application/main.tf#L33

All it does is simply not attempt to deploy changes if it thinks the Rancher ID will change. Here is some documentation on how it works: https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes

@gargath If this works for you as a solution we can move this ticket to done
