### ISSUE TITLE
Add admin cluster to installer (step 04)

### ISSUE THREAD

**Issue by Kirsten-Osborn** [filetrust/Glasswall-ICAP-Platform#351]
Check that installation package also deploys admin cluster

**Comment by sirspen** [comment]
From what I can tell, the admin cluster should be deployed in step 04_rancher-clusters of the install package. 
https://github.com/filetrust/Glasswall-ICAP-Platform/blob/main/environments/installer/04_rancher-clusters/main.tf#L21
https://github.com/filetrust/Glasswall-ICAP-Platform/blob/main/workspace/icap-multi-cluster-no-vault/main.tf#L165

If this is incorrect, @khoovirajsingh , move it back to in progress and I will look into it further.
