### ISSUE TITLE
Test docker pull secret

### ISSUE THREAD

**Issue by Kirsten-Osborn** [filetrust/Glasswall-ICAP-Platform#355]

**Comment by sirspen** [comment]
Testing this, it seems like the way we generate the secret is incorrect. As of right now, we create the token via `az acr login --name <container registry name> --expose-token`. But this only creates a token that lasts about an hour. For the ability to reuse the secret to pull images  we need to create the secret as per https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes#create-an-image-pull-secret. I've added a comment in the documentation
