### ISSUE TITLE
After couple of load test UKS Rancher Cluster returning all 500 errors

### ISSUE THREAD

**Issue by dpatel7** [filetrust/Glasswall-ICAP-Platform#362]
Started 5 load of 15 min in total. manage to get first 4 with 4% error rate then when run the 5th test can't get any successes.
![2021-02-10_20h45_47](https://user-images.githubusercontent.com/61416876/107628325-673e7380-6c58-11eb-908d-24acab71f598.png)

Link to Dashboard - http://52.50.212.61:3000/d/uQghbvPMz/ranchertest5-icap-live-performance-dashboard?orgId=1&refresh=5s

**Comment by dpatel7** [comment]
seeing issue on etcd d1 
![image](https://user-images.githubusercontent.com/61416876/107630526-90143800-6c5b-11eb-8979-17efbf2680b6.png)

**Comment by Kirsten-Osborn** [comment]
Closing as duplicated of #363 - this problem arose during the deployment to Prod this morning, and is scheduled to be resolved this afternoon
