### ISSUE TITLE
Prepare environment for Wed AM installation continuation session

### ISSUE THREAD

**Issue by Kirsten-Osborn** [filetrust/Glasswall-ICAP-Platform#394]
Environment needs to be complete up to and including step 6.3.5	Deploy Rancher Server, so that training session can resume at step 6.3.6	Deploy the adaptation and administration clusters.

**Comment by sirspen** [comment]
OK, this was caused because the images were pulled from the the old `add-image-registry
` branch of `icap-infrastructure`. I'm uploading the new images from the newer `rancher-develop` branch now
