### ISSUE TITLE
Identify and complete merge requests required

### ISSUE THREAD

**Issue by Kirsten-Osborn** [filetrust/Glasswall-ICAP-Platform#98]
Start date: N/A
End date: 17/11/20

Merge git-server-for-rancher branch on Glasswall-ICAP-Platform main repo

Convert add-image-registry branch to a long live branch on icap-infrastructure repo

**Comment by sylvester-loreto-codurance** [comment]
https://github.com/filetrust/icap-infrastructure/pull/73
